apps/core/urls.py
from django.urls import path

from . import views

app_name = 'core_app'
urlpatterns = [
    path('', views.frontpage, name='frontpage'),
    path('contact/', views.contact, name='contact'),
]

interiorShop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('vendors/', include('apps.vendor.urls')),
    path('cart/', include('apps.cart.urls')),
    path('', include('apps.product.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                            document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.db import models

# Create your models here.

apps/core/views.py
from django.shortcuts import render
from apps.product.models import Product
# Create your views here.

def frontpage(request):
    newest_products = Product.objects.all()[0:8]
    return render(request, 'core/frontpage.html', {'newest_products':newest_products})


def contact(request):
    return render(request, 'core/contact.html')

apps/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css" />
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    <script src="{% static 'scripts/main.js' %}"></script>
</head>
{% block extra_head %} front page{% endblock extra_head %}
<body>
    <nav class="navbar is-dark">
        <div class="navbar-brand">
            <a href="#" class="navbar-item"><strong>Interiorshop</strong></a>

            <a role="button" class="navbar-burge" aria-label="menu" aria-expanded="false" data-target="main-navbar">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>
        <div class="navbar-menu" id="main-navbar">
            <div class="navbar-start">
                <div class="navbar-item">
                    <form action="{% url 'search' %}" method="get">
                        <div class="field has-addons">
                            <div class="control">
                                <input type="text" placeholder="Search..." name="query" class="input">
                            </div>
                            <div class="control">
                                <button class="button is-dark is-uppercase">Search</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="navbar-end">
                {% for category in menu_categories %}
                    <a href="{% url 'category' category.slug %}" class="navbar-item">{{ category.title }}</a>
                {% endfor %}
                    <a href="{% url 'core_app:contact' %}" class="navbar-item">Contact</a>

                    <div class="navbar-item">
                        <a href="{% url 'cart' %}" class="button is-dark">Cart{% if cart %} ({{ cart|length }}){% endif %}</a>
                    </div>
            </div>
        </div>
    </nav>
    <section class="section">
        <div class="container">
            {% block content %}

            {% endblock %}        
        </div>
    </section>
    <footer class="footer">
        <h3 class="is-size-4 mb-4">InteriorShop</h3>
        {% if request.user.is_authenticated %}
        <a href="{% url 'vendor_app:vendor_admin' %}">Vendor Admin</a>
        {% else %}
        <a href="{% url 'vendor_app:become_vendor' %}">Become Vendor</a>
        {% endif %}
        <a href="{% url 'vendor_app:vendors' %}">Vendors</a>
    </footer>
    {% block scripts %}{% endblock scripts %}
</body>
{% block extra_body %}{% endblock extra_body %}
</html>

apps/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %} Contact {% endblock title %}

{% block content %}
    <h1>Contact</h1>
{% endblock %}

apps/core/templates/core/frontpage.html
{% extends 'core/base.html' %}
{% block title %} Welcome|InteriorShop {% endblock title %}
{% block content %}
<h1>Front page</h1>
    <div class="columns is-multiline mb-6">
        <div class="column is-12 has-text-centered mt-6 mb-6">
            <h2 class="is-size-3">Newest Products</h2>
        </div>
        {% for product in newest_products %}
        {% include 'product/parts/list_item.html' %}
        {% endfor %}
    </div>
{% endblock %}